//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Associacao
    {
        public int SaidaId { get; set; }
        public int EntradaId { get; set; }
        public int QtdAssociada { get; set; }
    
        public virtual Entrada Entrada { get; set; }
        public virtual Saida Saida { get; set; }
    }
}
