//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtivoUltimoPreco
    {
        public string Codigo { get; set; }
        public System.DateTime Data { get; set; }
        public decimal PrecoUltimo { get; set; }
    
        public virtual Ativo Ativo { get; set; }
    }
}
