//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarioItem
    {
        public short Ano { get; set; }
        public short Mes { get; set; }
        public int PagamentoID { get; set; }
        public bool Agendado { get; set; }
        public Nullable<System.DateTime> AgendadoData { get; set; }
        public bool Pago { get; set; }
        public Nullable<System.DateTime> PagamentoData { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<int> BalanceID { get; set; }
    
        public virtual Pagamento Pagamento { get; set; }
    }
}
