//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarteiraAtivo
    {
        public int CarteiraID { get; set; }
        public string Codigo { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
    
        public virtual Carteira Carteira { get; set; }
    }
}
