//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fundo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fundo()
        {
            this.Contas = new ObservableListSource<ContaFundo>();
            this.Meses = new ObservableListSource<FundoMes>();
            this.Rentabilidades = new ObservableListSource<Rentabilidade>();
        }
    
        public int ID { get; set; }
        public string Nome { get; set; }
        public string CNPJ { get; set; }
        public string Apelido { get; set; }
        public string Tipo { get; set; }
        public string NomeTabRent { get; set; }
        public Nullable<decimal> TaxaAdmin { get; set; }
        public string Aplicacao { get; set; }
        public string Resgate { get; set; }
        public Nullable<int> BancoID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<ContaFundo> Contas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<FundoMes> Meses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<Rentabilidade> Rentabilidades { get; set; }
    }
}
