//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LCA()
        {
            this.LCAMeses = new ObservableListSource<LCAMes>();
        }
    
        public int ID { get; set; }
        public int ContaID { get; set; }
        public string Numero { get; set; }
        public System.DateTime Aplicacao { get; set; }
        public System.DateTime Vencimento { get; set; }
        public decimal Taxa { get; set; }
        public decimal ValorEmissao { get; set; }
    
        public virtual Conta Conta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<LCAMes> LCAMeses { get; set; }
    }
}
