//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCAMovimento
    {
        public int ID { get; set; }
        public int LCAMesId { get; set; }
        public System.DateTime Data { get; set; }
        public string Historico { get; set; }
        public decimal ValorCapital { get; set; }
        public decimal ImpostoRenda { get; set; }
        public decimal IOF { get; set; }
        public decimal Rendimentos { get; set; }
        public decimal ValorMovimento { get; set; }
        public decimal ValorAtual { get; set; }
    
        public virtual LCAMes LCAMes { get; set; }
    }
}
