//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimento
    {
        public int MovimentoId { get; set; }
        public int ContaMesId { get; set; }
        public System.DateTime Data { get; set; }
        public string Historico { get; set; }
        public decimal Valor { get; set; }
        public decimal ImpostoRenda { get; set; }
        public decimal IOF { get; set; }
        public decimal CotaQtd { get; set; }
        public Nullable<decimal> CotaValor { get; set; }
    
        public virtual ContaMes ContaMes { get; set; }
    }
}
