//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SerieHistorica
    {
        public string Codigo { get; set; }
        public System.DateTime Data { get; set; }
        public decimal PrecoAbertura { get; set; }
        public decimal PrecoMaximo { get; set; }
        public decimal PrecoMinimo { get; set; }
        public decimal PrecoMedio { get; set; }
        public decimal PrecoUltimo { get; set; }
        public decimal PrecoMelhorOfertaCompra { get; set; }
        public decimal PrecoMelhorOfertaVenda { get; set; }
    
        public virtual Ativo Ativo { get; set; }
    }
}
