//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    
    public partial class SituacaoImpostoRenda
    {
        public string Codigo { get; set; }
        public Nullable<int> Qtd { get; set; }
        public decimal Preco { get; set; }
        public Nullable<decimal> Total { get; set; }
    }
}
